on:
  pull_request: 
    types:
    - opened
  
jobs:
  testing-action:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Post PR Comment
      id: giphy
      uses: ./
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        giphy-api-key: ${{ secrets.GIPHY_API_KEY }}

    - name: Log Comment URL
      run: echo "URL - ${{ steps.giphy.outputs.pr-comment-url }}"